#!/bin/bash
PROJECT_ROOT="$(dirname $(readlink -f "${BASH_SOURCE[0]}"))/.."
DOCKER_COMPOSE_FILE="${PROJECT_ROOT}/docker-compose.yaml"
CURRENT_DIR=$(pwd)

if [[ ${CURRENT_DIR} =~ /scripts$ ]]; then
        echo "Please run this script from the ticketbot root folder, not the scripts directory."
        echo "To do this, change up one directory, and then run the following command:"
        echo "./scripts/start"
        exit 1
fi


if [ "$EUID" -eq 0 ]
  then echo "Error: ticketbot should not be run as root."
  exit 1
fi

docker compose \
  -f $DOCKER_COMPOSE_FILE \
  up --build --remove-orphans $@
